### ISSUE TITLE
Singularity fails to build

### ISSUE THREAD

**Issue by ashwinvis** [omuse-geoscience/omuse#28]
Following up https://bitbucket.org/omuse/omuse/issues/19/singularity-recipe-fails-to-build

Installation progresses, but fails later on :
```bash
Building wheels for collected packages: mpi4py
  Building wheel for mpi4py (setup.py) ... done
  Created wheel for mpi4py: filename=mpi4py-3.0.3-cp36-cp36m-linux_x86_64.whl size=2550550 sha256=31350a25826377bd13c2d97a9256868749d407fad9577284353a37da614c9652
  Stored in directory: /root/.cache/pip/wheels/d6/73/83/ad9dd3ebae512829ab3f21657f76403dc4aa6649e1118c9369
Successfully built mpi4py
Installing collected packages: wheel, pluggy, more-itertools, py, pytest, amuse-framework, mpi4py, omuse
  Attempting uninstall: wheel
    Found existing installation: wheel 0.31.1
    Uninstalling wheel-0.31.1:
      Successfully uninstalled wheel-0.31.1
  Running setup.py develop for omuse
Successfully installed amuse-framework-13.2.1 more-itertools-8.4.0 mpi4py-3.0.3 omuse pluggy-0.13.1 py-1.9.0 pytest-5.4.3 wheel-0.34.2
+ python3 setup.py build_code --code-name dales --inplace
running build_code
building libraries and community codes
build, for logging, see 'build.log'
[21:48:26] building dales
Community codes not built (because of errors):
================================================================================
 * dales
================================================================================
0 out of 1 codes built, 0 out of 0 libraries built
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    data_files=all_data_files,
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/omuse/support/setup_codes.py", line 1217, in run
    BuildCodes.run(self)
  File "/opt/omuse/support/setup_codes.py", line 1096, in run
    raise Exception("No succesful builds detected. Aborting.")
Exception: No succesful builds detected. Aborting.
FATAL:   failed to execute %post proc: exit status 1
FATAL:   While performing build: while running engine: while running /usr/libexec/singularity/bin/starter: exit status 255
```

NOTE: Using git tag v1.2:

commit caa7673c23406ccef1174836cdff2d7151d50f65 (HEAD, tag: v1.2)
Merge: 71ad0cd 930d266
Author: ipelupessy <i.pelupessy@esciencecenter.nl>
Date:   Mon Apr 6 12:11:36 2020 +0200

    Merge branch 'master' of github.com:omuse-geoscience/omuse****

**Comment by ashwinvis** [comment]
I am able to build and run dales locally without Singularity (on Arch Linux) though.

**Comment by ashwinvis** [comment]
I agree with @fjansson that the versions should be pinned for the sake of reproducibility. Not just Python packages, but perhaps also the OS, which is loosely pinned:

https://github.com/omuse-geoscience/omuse/blob/caa7673c23406ccef1174836cdff2d7151d50f65/Singularity#L23-L24

See https://hub.docker.com/_/centos?tab=tags.

Another alternative would be build the singularity image and upload it somewhere safe.

**Comment by fjansson** [comment]
Thank you @ashwinvis for reporting the build failure, and sorry for the slow response. I just tested building the image on Arch Linux, and got a similar failure, which turned out to be caused by CMake not liking that the DALES build directory already exists:
```
CMake Error: The current CMakeCache.txt directory /opt/omuse/src/omuse/community/dales/dales-build/CMakeCache.txt is different than the directory /home/fjansson/work_F/cwi-code/omuse/src/omuse/community/dales/dales-build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
```
I think building OMUSE and DALES in-place without singularity before trying to build the singularity image causes this. After removing the dales-build directory, I succeeded in building the image. I think a better fix would be to ensure that these paths don't collide.

A way to view the build.log file is to use the sandbox option and request that the files are not removed if the build fails:
```
sudo singularity build --no-cleanup -s sandbox Singularity
less rootfs-xxxx/opt/omuse/build.log
```

For pinning the OS version: I see the base image we use, `centos:8` is being updated, and that there are tagged versions e.g. centos:8.2.2004 which presumably stay unchanged.  But our current recipe anyway uses yum to install dependencies (and the recipe starts with a yum update) so I think pinning the base image is not a guarantee that nothing will change (although I'd expect centos updates to be rather conservative exactly for the reason that they don't want to break things). I'd be in favour of archiving a known-good image as well as the recipe.

Good news in the centos:8 image being updated is that the OpenMPI bug there might have been fixed, if so we can stop building it manually in the recipe. I'll test this.

**Comment by ashwinvis** [comment]
I must also confide I did not see the debugging instructions among the comments. I confirm that I was getting the "CMake Error" and with a fresh clone I can build the image.

>  I think a better fix would be to ensure that these paths don't collide.

Yes that seems necessary. Either with an out-of-source build with CMake or ensuring that the sources are clean from build artifacts by doing a git-clone, for instance.
